version: '3.7'
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    command: bundle exec rails s puma -p 3000 -b '0.0.0.0'
    volumes:
      - .:/Dojo
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    tty: true
    stdin_open: true
volumes:
  postgres:
    driver: local
  bundle:
