version: '3'
services:
  db:
    image: postgres:11.1
    volumes:
      - pg:/var/lib/postgresql/data
  web:  
    build: .
    command: bundle exec rails s puma -b 0.0.0.0 -p 3000
    volumes:
      - .:/sperant
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  pg:
    driver: local
