services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vitualizz-devstack
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - devstack-logs:/root/.vitualizz-devstack

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: vitualizz-devstack-test
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "test", "./...", "-v"]

  shell:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vitualizz-devstack-shell
    stdin_open: true
    tty: true
    entrypoint: ["/bin/sh"]

volumes:
  devstack-logs: